### ISSUE TITLE
Contacts not Syncing and Call Logs are not Auto-Logging

### ISSUE THREAD

**Issue by jin-fhg** [ringcentral/redtail-embeddable-ringcentral-phone#34]
Hello @zxdong262, 

We are receiving issues from our customer with the RedTail Integration where the Authorize button does not seem to sync the contacts when he clicks it. It does not also save the logs and associate it with the contact. I have gathered a short video of this issue, I also checked the cookies settings in Chrome and they were enabled to be saved. Please let me know if you need more information: 

https://drive.google.com/file/d/1KDjc_L-nNUwStYo3fyNyq3iy9Obrj6HW/view?usp=sharing

**Comment by zxdong262** [comment]
<img width="971" alt="Screen Shot 2020-03-31 at 7 32 50 AM" src="https://user-images.githubusercontent.com/1641949/77971688-ed441b00-7321-11ea-9263-fbc5e039e593.png">
Need click the auth button in the screenshot

**Comment by jin-fhg** [comment]
Hello @zxdong262 , 

The video also showed that the Calls are not being logged to the contacts because the Redtail Contacts are not being detected. Is there a specific phone number format that we have to strictly follow so that the logs can be detected?

**Comment by zxdong262** [comment]
Only after authorization, synced all contact data, call log would work @jin-fhg

**Comment by zxdong262** [comment]
@jin-fhg In setting there is a region can be set, for the phone number belong to this region, no country code needed, for phone number not belong to this region, must have country code, like +86 xxxxx, and must have the "+".

**Comment by jin-fhg** [comment]
Hello @zxdong262 

Thank you for that information. If you may ask another question, may I know how long roughly does it take for about 3000 contacts to be synced? Do they need to keep the RC Embedabble widget open for that? 

Thank you.

**Comment by zxdong262** [comment]
@jin-fhg Maybe one hour or more time, need wait until it finish, do not close the page and widget.

**Comment by jin-fhg** [comment]
Hello @zxdong262 , 

We tried to sync the data and left the browser and the widget open for a whole day, but it is only syncing some of the contacts. Here are the HAR and console logs.

https://drive.google.com/file/d/1ZUaQIPqAzA2ebx8hm118GK2gSMQ8W2Aq/view?usp=sharing

https://drive.google.com/file/d/1pMe3BwCTCCwb5nnCD9_AlBdGQzT-Lj8p/view?usp=sharing

**Comment by zxdong262** [comment]
@jin-fhg Did your session expires? It may expires before the sync finished, you can click resync button again, it will sync from last sync point, again and again, until you see it shou finish notification.

**Comment by zxdong262** [comment]
@jin-fhg Also I released new version, you can try it, now it use in page widgets.

**Comment by DrTrout** [comment]
So there is a different app now than the Chrome extension? 

It still does not work for me. I can see the trouble the app would have since we have 15,000 contacts in our database. Unless Redtail gives you the ability to select certain Quicklists or Tag Groups, then this solution probably isn't going to work as we do not need to synch 15k records. 






Mark S. Starosciak, CFP ® | Managing Partner 

Infinium Investment Advisors, LLC 
[ callto:(720) 253-1818 | (720) 253-1818 ] x2 



To schedule a call with me, please click here: [ http://t.sidekickopen05.com/s1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg3N1N-FW5vMqvY1p7Y5sVRzDdF56dwBCf7plV4R02?t=https%3A%2F%2Fwww.timetrade.com%2Fbook%2F2QLRJ&si=6673796014800896&pi=af098a6a-c5f3-4acb-ab2c-8da36c706519 | Mark's Calendar ] 



DISCLOSURE: electronic mail sent through the Internet is not secure and could be intercepted by a third party. For your protection, avoid sending identifying information such as account, Social Security, or card numbers to us or others. Further, do not send time-sensitive, action-oriented messages such as transaction orders, fund transfer instructions or check stop payments, as it is our policy not to accept such items electronically. This message w/attachments (message) may be privileged, confidential or proprietary, and if you are not an intended recipient, please notify the sender, do not use or share it and delete it. Unless specifically indicated, this message is not an offer to sell or a solicitation of any investment products or other financial product or service, an official confirmation of any transaction, or an official statement of Infinium Investment Advisors. Subject to applicable law, Infinium Investment Advisors may monitor, review and retain e-communications (EC) traveling through its networks/systems. The laws of the country of each sender/recipient may impact the handling of EC, and EC may be archived, supervised and produced in countries other than the country in which you are located. This message cannot be guaranteed to be secure or error-free. Attachments that are part of this E-communication may have additional important disclosures and disclaimers, which you should read

**Comment by zxdong262** [comment]
@DrTrout No, there is no other app, just released new version of this app. what kind of contact group you want to sync, can you give a example? Does this group has a url can accessed?

**Comment by DrTrout** [comment]
Please close this ticket. RingCentral is not going to work for our company. I appreciate all of your help! 






Mark S. Starosciak, CFP ® | Managing Partner 

Infinium Investment Advisors, LLC 
[ callto:(720) 253-1818 | (720) 253-1818 ] x2 



To schedule a call with me, please click here: [ http://t.sidekickopen05.com/s1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg3N1N-FW5vMqvY1p7Y5sVRzDdF56dwBCf7plV4R02?t=https%3A%2F%2Fwww.timetrade.com%2Fbook%2F2QLRJ&si=6673796014800896&pi=af098a6a-c5f3-4acb-ab2c-8da36c706519 | Mark's Calendar ] 



DISCLOSURE: electronic mail sent through the Internet is not secure and could be intercepted by a third party. For your protection, avoid sending identifying information such as account, Social Security, or card numbers to us or others. Further, do not send time-sensitive, action-oriented messages such as transaction orders, fund transfer instructions or check stop payments, as it is our policy not to accept such items electronically. This message w/attachments (message) may be privileged, confidential or proprietary, and if you are not an intended recipient, please notify the sender, do not use or share it and delete it. Unless specifically indicated, this message is not an offer to sell or a solicitation of any investment products or other financial product or service, an official confirmation of any transaction, or an official statement of Infinium Investment Advisors. Subject to applicable law, Infinium Investment Advisors may monitor, review and retain e-communications (EC) traveling through its networks/systems. The laws of the country of each sender/recipient may impact the handling of EC, and EC may be archived, supervised and produced in countries other than the country in which you are located. This message cannot be guaranteed to be secure or error-free. Attachments that are part of this E-communication may have additional important disclosures and disclaimers, which you should read
